username: admin
password: secret
role: user

logging:
  level:
    root: info 

management:
  security:
    enabled: false

spring:
  datasource:
    continue-on-error: true   # The script will throw an exception if the table exists, so suppress the error
    
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: password
---

spring:
  profiles: test
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    url: jdbc:db2://localhost:50000/sample
    username: db2inst1
    password: password
    
  
